// flow-typed signature: 09da354b2e0cf2235ec9eff5337f6595
// flow-typed version: <<STUB>>/connected-react-router_v6.8.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  declare module.exports: any;
}

declare module 'connected-react-router/immutable' {
  declare module.exports: any;
}
