// flow-typed signature: 18db11b74669fbb7a7181f34fc1c76ce
// flow-typed version: <<STUB>>/immutable_v4.0.0-rc.12/flow_v0.99.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable' {
  declare module.exports: any;
}
