// flow-typed signature: f91972d7e7f606d298caf5cb9ff12525
// flow-typed version: <<STUB>>/lattice_v0.53.1/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lattice'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lattice' {
  declare module.exports: any;
}
